function init(self)

	msg.post(".", "acquire_input_focus") -- <1>
	print("READY")
	self.asdf = false
end


function on_message(self, message_id, message, sender)
	
	
end

function on_input(self, action_id, action)
	if action_id == hash("store_nut") and not self.asdf then 
		msg.post(".", "release_input_focus")
		msg.post("start:/go#screen_manager", "play_screen")
		self.asdf = true 
		self.loader = self
	end
end
